language: node_js
node_js:
  - "10"
branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - "node_modules"

jobs:
  include:
    - stage: publish
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s
        - export PATH="$HOME/.yarn/bin:$PATH"
      before_script:
        - yarn install
      script:
        - yarn test
      before_deploy:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      deploy:
        provider: script
        before_script:
          - yarn lerna-semantic-release pre
        script: yarn lerna-semantic-release perform
        skip_cleanup: true
        on:
          branch: master
