language: node_js
node_js:
  - "12"
branches:
  only:
    - master

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: publish
      before_install: .travis/before_install.sh
      script: yarn build
      deploy:
        - provider: script
          script: yarn release
          skip_cleanup: true
          on:
            branch: master

        - provider: script
          script: yarn npm:publish
          skip_cleanup: true
          on:
            branch: master
