language: node_js
node_js:
  - "12"
branches:
  only:
    - master

cache:
  directories:
    - node_modules

env:
  global:
    - GITHUB_REPO: theBenForce/data-migration
    - GIT_SOURCE: _docpress

jobs:
  include:
    - stage: publish
      name: "Deploy Packages"
      before_install: .travis/before_install.sh
      script: yarn release
      skip_cleanup: true
      on:
        branch: master
      deploy:
        - provider: script
          script: yarn npm:publish
          skip_cleanup: true
          on:
            branch: master

        - provider: script
          script: .travis/deploy_pages.sh
          skip_cleanup: true
          on:
            branch: master
