name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: semantic-release puglishing
        run: |
          yarn install
          yarn lerna-semantic-release pre
          yarn lerna-semantic-release perform
          yarn lerna-semantic-release post
