name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: lerna publishing
        run: |
          yarn install
          yarn run init
          git update-index --assume-unchanged packages/swallow-cli/yarn.lock packages/swallow-migration/yarn.lock plugins/swallow-cognito/yarn.lock plugins/swallow-processor-cf/yarn.lock
          yarn lerna publish patch --yes
