name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: lerna publishing
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          yarn install
          yarn run init
          git update-index --assume-unchanged ./**/yarn.lock
          yarn lerna publish from-package --yes --no-git-reset
